version: "3"
services:
  docker-mysql:
    image: docker-mysql
    ports:
      - "8090:8090"
    networks:
      - employee-mysql
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    networks:
      - employee-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dockerdb  

networks:
  employee-mysql: 